# Generated by Django 2.2.28 on 2024-08-02 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20240802_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bill'),
        ),
        migrations.AlterField(
            model_name='household',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('period_type', models.CharField(max_length=128)),
                ('frequency', models.IntegerField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Household')),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='chore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Chore'),
        ),
    ]
