# Generated by Django 2.2.28 on 2024-08-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240802_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='slug',
            field=models.SlugField(default='default'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
